### ISSUE TITLE
ST3: have to reload plugin to get it to work

### ISSUE THREAD

**Issue by michel-m** [biermeester/Pylinter#32]
Hi,

I'm having this issue on ST3 (3047), on both Windows (8) and Linux (Ubuntu 13.04).
ST3 starts, loads the plugin without issue, then when I _ctrl + alt + z_, it says in the console:

`Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "C:\Users\john\AppData\Roaming\Sublime Text 3\Packages\Pylinter\pylinter.py", line 194, in run
    settings = PylSet.read_settings()
  File "C:\Users\john\AppData\Roaming\Sublime Text 3\Packages\Pylinter\pylinter.py", line 86, in read_settings
    python_path = PATH_SEPERATOR.join([str(p) for p in python_path])
TypeError: 'NoneType' object is not iterable`

If I reload the plugin (for instance by disabling and re-enabling it, or by changing something in _pylinter.py_ and saving the file), it works well. I'm quite confident I didn't do any mistake settings-wise, but I can post it here on demand.
Anyway, if anyone experiences the same problem as I do, please speak up.

Also, thanks a lot for this handy plugin!

**Comment by biermeester** [comment]
Weird weird weird :)

So when does Pylinter start to fail? When ST3 is first launched? After every use? When you launch it using the keyboard shortcut?
And when you get it working again, how long does it last? Until the next time you run ST3?

Since I have no clue what could be the cause yet, please post both your `Data\Packages\User\Pylinter.sublime-settings` and `Data\Packages\Pylinter\Pylinter.sublime.settings` files.

Thanks in advance!

**Comment by michel-m** [comment]
When ST3 is first launched, it says in the console:

```
[...]
reloading plugin Pylinter.multiconf
reloading plugin Pylinter.pylinter
plugins loaded
```

Then pylinter doesn't work (neither by saving a _.py_ file, nor by using the keyboard shortcut), until I reload the plugin somehow (disabling then re-enabling it, or editing the _pylinter.py_ file and saving it). Once it has been reloaded, it works until the next time I run ST3.

My `User/Pylinter.sublime-settings` is empty. Here is the content of my `Pylinter/Pylinter.sublime.settings`:

```
{
    "verbose": true,
    "python_bin": "python",
    "python_path": [

                   ],
    "working_dir": null,
    "pylint_path": null,
    "pylint_rc": null,
    "run_on_save": true,
    "use_icons": true,
    "disable_outline": false,
    "message_stay": true,
    "ignore": [],
    "disable": []
}
```

Also, I'm using a virtualenv, so I set my project settings file as such:

```
{
    "folders":
    [
        {
            "follow_symlinks": true,
            "path": "project/project"
        }
    ],
    "settings":
    {
        "pylinter":
        {
            "python_bin": "/home/john/dev/project_venv/bin/python",
            "python_path": [
                            "/home/john/dev/project_venv/lib/python2.7/site-packages/",
                            "/home/john/dev/project/project/",
                           ],
            "working_dir": "/home/john/dev/project/project/",
            "pylint_path": "/home/john/dev/project_venv/lib/python2.7/site-packages/pylint/lint.py",
            "pylint_rc": "/home/john/dev/project/project/.pylintrc"
        }
    }
}
```

I also tried without virtualenv, with my `Pylinter/Pylinter.sublime.settings` looking like:

```
{
    "verbose": true,
    "python_bin": "python",
    "python_path": [
                     "/home/john/dev/project/project/",
                   ],
    "working_dir": null,
    "pylint_path": "/usr/lib/python2.7/dist-packages/pylint/lint.py",
    "pylint_rc": "/home/john/.pylintrc",
    "run_on_save": true,
    "use_icons": true,
    "disable_outline": false,
    "message_stay": true,
    "ignore": [],
    "disable": []
}
```

Thanks!

(Please note that yesterday I posted from Windows, now from Linux, hence the change in the various paths.)

**Comment by biermeester** [comment]
Thanks for the detailed info, I'll try and have a look at it later today.

**Comment by zonksoft** [comment]
I have exactly the same issue. I have the default settings of pylinter. It works again after disabling/enabling or uninstall/install. After a restart of Sublime, it never works.

**Comment by biermeester** [comment]
Ok, on the one hand, good to know. On the other hand, when I run Pylinter with a default configuration using ST3 on Windows, I don't encounter any problems. What OS are you using, @zonksoft ?

**Comment by zonksoft** [comment]
opensuse 12.3. I can also try it on Ubuntu 13.04 tomorrow.

**Comment by biermeester** [comment]
I deleted my User Pylinter settings on Ubuntu 12 and I see the error now. Going to try and fix it now.

**Comment by biermeester** [comment]
The settings in ST3 are now loaded using the API `plugin_loaded` callback, which should fix this problem.

**Comment by arusahni** [comment]
I'm still having this issue with the latest ST3 and Pylinter (Ubuntu 13.04, x64):

```
error: Pylint not found at 'lint.py'.
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1023, in load_module
  File "<frozen importlib._bootstrap>", line 1004, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 869, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/aru/.config/sublime-text-3/Packages/Pylinter/pylinter.py", line 161, in <module>
    PYLINT_VERSION = PylSet.get_lint_version()
  File "/home/aru/.config/sublime-text-3/Packages/Pylinter/pylinter.py", line 152, in get_lint_version
    os.path.dirname(PylSet.get_lint_path()),
  File "X/posixpath.py", line 151, in dirname
AttributeError: 'NoneType' object has no attribute 'rfind'
```

``` json
{
    // When versbose is 'true', various messages will be written to the console.
    // values: true or false
    "verbose": true,
    // The full path to the Python executable you want to
    // run Pylint with or simply use 'python'.
    "python_bin": "/home/aru/code/project/deps/venv/bin/python",
    // The following paths will be added Pylint's Python path
    "python_path": [ ],
    // Optionally set the working directory
    "working_dir": null,
    // Full path to the lint.py module in the pylint package
    "pylint_path": "/home/aru/code/project/deps/venv/lib/python2.7/site-packages/pylint/lint.py",
    // Optional full path to a Pylint configuration file
    "pylint_rc": "/home/aru/code/dotfiles/pylintrc",
    // Set to true to automtically run Pylint on save
    "run_on_save": true
}
```

When I force a reload of the plugin, it finds and loads my pylint just fine.
