### ISSUE TITLE
pylint_path setting ignored at startup

### ISSUE THREAD

**Issue by dpwrussell** [biermeester/Pylinter#34]
This is a "Pylint not found at 'lint.py'" error. On Mac OSX.

Basically, I installed pylinter into ST3 (commit: be4e76e12d) and pylint into a virtualenv. pylint_path is not picked up properly when Sublime starts, resulting in:

```
reloading plugin Pylinter.multiconf
reloading plugin Pylinter.pylinter
pylint_pathSTART
None
pylint_pathEND
error: Pylint not found at 'lint.py'.
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1023, in load_module
  File "<frozen importlib._bootstrap>", line 1004, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 869, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/dpwrussell/Library/Application Support/Sublime Text 3/Packages/Pylinter/pylinter.py", line 164, in <module>
    PYLINT_VERSION = PylSet.get_lint_version()
  File "/Users/dpwrussell/Library/Application Support/Sublime Text 3/Packages/Pylinter/pylinter.py", line 155, in get_lint_version
    os.path.dirname(PylSet.get_lint_path()),
  File "X/posixpath.py", line 151, in dirname
AttributeError: 'NoneType' object has no attribute 'rfind'
plugins loaded
```

This snippet in there is some debug code I added to do:

```
settings_obj.get('pylint_path')
```

```
pylint_pathSTART
None
pylint_pathEND
```

As you can see, the path is initially None and thus pylinter does not work.

I've tried setting it in project settings in a pylinter section, in Pylinter User settings (~/Library/Application Support/Sublime Text 3/Packages/User/Pylinter.sublime-settings) and finally in the main settings file itself (~/Library/Application Support/Sublime Text 3/Packages/Pylinter.sublime-settings). All to no avail.

In the latter two, my config section looked like this

```
{
//...
"python_bin": "/Users/dpwrussell/.virtualenvs/test_sublime/bin/python",
"pylint_path": "/Users/dpwrussell/.virtualenvs/test_sublime/lib/python3.3/site-packages/pylint/lint.py",
}
```

Oddly, when adding my debug code I discovered something surprising. When I edited pylinter.py, it starts working:

```
Writing file /Users/dpwrussell/Library/Application Support/Sublime Text 3/Packages/Pylinter/pylinter.py with encoding UTF-8 (atomic)
reloading plugin Pylinter.pylinter
pylint_pathSTART
/Users/dpwrussell/.virtualenvs/test_sublime/lib/python3.3/site-packages/pylint/lint.py
pylint_pathEND
```

If you restart Sublime it stops working until you modify pylinter.py again.

Happy to help debug this if you need someone on OSX.

**Comment by daogilvie-9fin** [comment]
Having a similar issue, but I've found a workaround that involves a small edit to pylinter.py. I have forked to do the change. Will issue a pull-request momentarily - I'm not sure if this is the most appropriate solution, but it works reliably for me at this time.

**Comment by daogilvie-9fin** [comment]
Apologies, I think this doesn't solve the issue after all, I am mistaken. It appears none of the settings are there until the module is reloaded, similar to issue 32. My testing environment was corrupted, and I thought I'd made progress where I really had not.

**Comment by daogilvie-9fin** [comment]
Think I have actually fixed it. Submitted a pull request for your perusal :)

**Comment by biermeester** [comment]
Thank you both for the feedback!

**Comment by dpwrussell** [comment]
Are you planning to merge that pull request or otherwise fix it? Otherwise doesn't make a lot of sense to close this Issue.

Thanks.

**Comment by biermeester** [comment]
Yes, I'm planning on a merge tonight. But I've learned not to be too optimistic, so I want to do some tests first. 
See #35

**Comment by biermeester** [comment]
@dpwrussell I've pushed a little update which should handle the failure to find `lint.py` a bit better. I also noticed that everything works fine, as long as you launch SublimeText from a Virtualenv that has Pylint installed. Could you please check if that 'solves' your problem for the time being?

I'm thinking about adding support for Virtualenv, where you can just set the name of the Virtualenv in the configuration, but it will be a few days before I have time to look into importing the right variabels. (Just finding `lint.py` won't be enough, since Pylint won't be able to find any import etc.)

**Comment by dpwrussell** [comment]
@biermeester I tried the latest. I still get the error on startup and in addition. When I save and pylinter is run:

```
Fatal pylint error:
lint.py: error: no such option: --include-ids
```

Unless launched from a virtulenv, then it works fine. As you say, it's not a long term solution, but it's working for now.
